//! Single source of truth for all Spark operation classifications.
//! Rules reference these constants instead of maintaining their own lists.

// ── Shuffle-inducing operations ───────────────────────────────────────────────

/// Methods on a Spark DataFrame / RDD that trigger a shuffle (network data
/// exchange).  Used by PERF003 to count shuffle operations per file and by
/// F016 to recognise DataFrame method chains.
pub static SHUFFLE_OPS: &[&str] = &[
    // DataFrame / Dataset API
    "groupBy",
    "agg",
    "join",
    "crossJoin",
    "repartition",
    "distinct",
    "dropDuplicates",
    "orderBy",
    "sort",
    "sortWithinPartitions",
    // RDD API
    "reduceByKey",
    "groupByKey",
    "aggregateByKey",
    "combineByKey",
    "cogroup",
    "cartesian",
    "intersection",
    "subtractByKey",
    "leftOuterJoin",
    "rightOuterJoin",
    "fullOuterJoin",
];

// ── Checkpoint operations ─────────────────────────────────────────────────────

/// Methods that materialise a DataFrame / RDD to storage, resetting the
/// lineage.  Used by PERF003 as "free" reset points in the shuffle counter.
pub static CHECKPOINT_OPS: &[&str] = &["checkpoint", "localCheckpoint"];

// ── DataFrame-exclusive methods ───────────────────────────────────────────────

/// Methods that exist *only* on Spark DataFrames / related objects and never
/// on plain Python types (str, dict, list, …).
///
/// Used by F016 to decide whether an assignment RHS is a DataFrame chain, and
/// by any rule that needs to distinguish DataFrame calls from stdlib calls.
pub static DATAFRAME_METHODS: &[&str] = &[
    "__getattr__",
    "__getitem__",
    "agg",
    "alias",
    "approxQuantile",
    "asTable",
    "cache",
    "checkpoint",
    "coalesce",
    "colRegex",
    "collect",
    "columns",
    "corr",
    "count",
    "cov",
    "createGlobalTempView",
    "createOrReplaceGlobalTempView",
    "createOrReplaceTempView",
    "createTempView",
    "crossJoin",
    "crosstab",
    "cube",
    "describe",
    "distinct",
    "drop",
    "dropDuplicates",
    "dropDuplicatesWithinWatermark",
    "drop_duplicates",
    "dropna",
    "dtypes",
    "exceptAll",
    "executionInfo",
    "exists",
    "explain",
    "fillna",
    "filter",
    "first",
    "foreach",
    "foreachPartition",
    "freqItems",
    "groupBy",
    "groupingSets",
    "head",
    "hint",
    "inputFiles",
    "intersect",
    "intersectAll",
    "isEmpty",
    "isLocal",
    "isStreaming",
    "join",
    "limit",
    "lateralJoin",
    "localCheckpoint",
    "mapInPandas",
    "mapInArrow",
    "metadataColumn",
    "melt",
    "na",
    "observe",
    "offset",
    "orderBy",
    "persist",
    "plot",
    "printSchema",
    "randomSplit",
    "rdd",
    "registerTempTable",
    "repartition",
    "repartitionByRange",
    "replace",
    "rollup",
    "sameSemantics",
    "sample",
    "sampleBy",
    "scalar",
    "schema",
    "select",
    "selectExpr",
    "semanticHash",
    "show",
    "sort",
    "sortWithinPartitions",
    "sparkSession",
    "stat",
    "storageLevel",
    "subtract",
    "summary",
    "tail",
    "take",
    "to",
    "toArrow",
    "toDF",
    "toJSON",
    "toLocalIterator",
    "toPandas",
    "transform",
    "transpose",
    "union",
    "unionAll",
    "unionByName",
    "unpersist",
    "unpivot",
    "where",
    "withColumn",
    "withColumns",
    "withColumnRenamed",
    "withColumnsRenamed",
    "withMetadata",
    "withWatermark",
    "write",
    "writeStream",
    "writeTo",
    "mergeInto",
    "pandas_api",
];

// ── Column-only operations ────────────────────────────────────────────────────

/// Methods that live exclusively on `pyspark.sql.Column` and never on a
/// DataFrame.  Used to guard loop-detection rules (L001, L002) so that
/// expressions like `F.col(c).cast(...).alias(...)` inside a loop are not
/// mistaken for DataFrame lineage-accumulating calls.
pub static COLUMN_METHODS: &[&str] = &[
    "__getattr__",
    "__getitem__",
    "alias",
    "asc",
    "asc_nulls_first",
    "asc_nulls_last",
    "astype",
    "between",
    "bitwiseAND",
    "bitwiseOR",
    "bitwiseXOR",
    "cast",
    "contains",
    "desc",
    "desc_nulls_first",
    "desc_nulls_last",
    "dropFields",
    "endswith",
    "eqNullSafe",
    "getField",
    "getItem",
    "ilike",
    "isNaN",
    "isNotNull",
    "isNull",
    "isin",
    "like",
    "name",
    "otherwise",
    "outer",
    "over",
    "rlike",
    "startswith",
    "substr",
    "transform",
    "try_cast",
    "when",
    "withField",
];

// ── pyspark.sql.functions ─────────────────────────────────────────────────────

/// Every function exported from `pyspark.sql.functions` (called as `F.xyz(…)`
/// or `functions.xyz(…)`).  Stored as bare names without the module prefix.
///
/// Used to distinguish standalone function calls from DataFrame / Column method
/// calls when the two share the same name (e.g. `filter`, `count`, `coalesce`).
/// Rules that check method names should treat a hit in this list on a simple-Name
/// receiver (the common `F` / `functions` import alias pattern) as a functions
/// call, not a DataFrame method.
pub static SPARK_FUNCTIONS: &[&str] = &[
    // ── General ──────────────────────────────────────────────────────────────
    "broadcast",
    "call_function",
    "col",
    "column",
    "lit",
    "expr",
    // ── Null helpers ─────────────────────────────────────────────────────────
    "coalesce",
    "equal_null",
    "ifnull",
    "nanvl",
    "nullif",
    "nullifzero",
    "nvl",
    "nvl2",
    "when",
    "zeroifnull",
    // ── Predicate / pattern ───────────────────────────────────────────────────
    "ilike",
    "isnan",
    "isnotnull",
    "isnull",
    "like",
    "regexp",
    "regexp_like",
    "rlike",
    // ── Sorting helpers ───────────────────────────────────────────────────────
    "asc",
    "asc_nulls_first",
    "asc_nulls_last",
    "desc",
    "desc_nulls_first",
    "desc_nulls_last",
    // ── Math ──────────────────────────────────────────────────────────────────
    "abs",
    "acos",
    "acosh",
    "asin",
    "asinh",
    "atan",
    "atan2",
    "atanh",
    "bin",
    "bround",
    "cbrt",
    "ceil",
    "ceiling",
    "conv",
    "cos",
    "cosh",
    "cot",
    "csc",
    "degrees",
    "e",
    "exp",
    "expm1",
    "factorial",
    "floor",
    "greatest",
    "hex",
    "hypot",
    "least",
    "ln",
    "log",
    "log10",
    "log1p",
    "log2",
    "negate",
    "negative",
    "pi",
    "pmod",
    "positive",
    "pow",
    "power",
    "radians",
    "rand",
    "randn",
    "random",
    "rint",
    "round",
    "sec",
    "sign",
    "signum",
    "sin",
    "sinh",
    "sqrt",
    "tan",
    "tanh",
    "try_add",
    "try_divide",
    "try_mod",
    "try_multiply",
    "try_subtract",
    "unhex",
    "uniform",
    "width_bucket",
    // ── String ────────────────────────────────────────────────────────────────
    "ascii",
    "base64",
    "bit_length",
    "btrim",
    "char",
    "char_length",
    "character_length",
    "chr",
    "collate",
    "collation",
    "concat_ws",
    "contains",
    "decode",
    "elt",
    "encode",
    "endswith",
    "find_in_set",
    "format_number",
    "format_string",
    "initcap",
    "instr",
    "is_valid_utf8",
    "lcase",
    "left",
    "length",
    "levenshtein",
    "locate",
    "lower",
    "lpad",
    "ltrim",
    "make_valid_utf8",
    "mask",
    "octet_length",
    "overlay",
    "position",
    "printf",
    "quote",
    "randstr",
    "regexp_count",
    "regexp_extract",
    "regexp_extract_all",
    "regexp_instr",
    "regexp_replace",
    "regexp_substr",
    "repeat",
    "replace",
    "right",
    "rpad",
    "rtrim",
    "sentences",
    "soundex",
    "split",
    "split_part",
    "startswith",
    "substr",
    "substring",
    "substring_index",
    "to_binary",
    "to_char",
    "to_number",
    "to_varchar",
    "translate",
    "trim",
    "try_to_binary",
    "try_to_number",
    "try_validate_utf8",
    "ucase",
    "unbase64",
    "upper",
    "validate_utf8",
    // ── Bitwise ───────────────────────────────────────────────────────────────
    "bit_count",
    "bit_get",
    "bitwise_not",
    "getbit",
    "shiftleft",
    "shiftright",
    "shiftrightunsigned",
    // ── Date / time ───────────────────────────────────────────────────────────
    "add_months",
    "convert_timezone",
    "curdate",
    "current_date",
    "current_time",
    "current_timestamp",
    "current_timezone",
    "date_add",
    "date_diff",
    "date_format",
    "date_from_unix_date",
    "date_part",
    "date_sub",
    "date_trunc",
    "dateadd",
    "datediff",
    "datepart",
    "day",
    "dayname",
    "dayofmonth",
    "dayofweek",
    "dayofyear",
    "extract",
    "from_unixtime",
    "from_utc_timestamp",
    "hour",
    "last_day",
    "localtimestamp",
    "make_date",
    "make_dt_interval",
    "make_interval",
    "make_time",
    "make_timestamp",
    "make_timestamp_ltz",
    "make_timestamp_ntz",
    "make_ym_interval",
    "minute",
    "month",
    "monthname",
    "months_between",
    "next_day",
    "now",
    "quarter",
    "second",
    "session_window",
    "timestamp_add",
    "timestamp_diff",
    "timestamp_micros",
    "timestamp_millis",
    "timestamp_seconds",
    "time_diff",
    "time_trunc",
    "to_date",
    "to_time",
    "to_timestamp",
    "to_timestamp_ltz",
    "to_timestamp_ntz",
    "to_unix_timestamp",
    "to_utc_timestamp",
    "trunc",
    "try_make_interval",
    "try_make_timestamp",
    "try_make_timestamp_ltz",
    "try_make_timestamp_ntz",
    "try_to_date",
    "try_to_time",
    "try_to_timestamp",
    "unix_date",
    "unix_micros",
    "unix_millis",
    "unix_seconds",
    "unix_timestamp",
    "weekday",
    "weekofyear",
    "window",
    "window_time",
    "year",
    // ── Hash ──────────────────────────────────────────────────────────────────
    "crc32",
    "hash",
    "md5",
    "sha",
    "sha1",
    "sha2",
    "xxhash64",
    // ── Collection higher-order ───────────────────────────────────────────────
    "aggregate",
    "array_sort",
    "cardinality",
    "concat",
    "element_at",
    "exists",
    "filter",
    "forall",
    "map_filter",
    "map_zip_with",
    "reduce",
    "reverse",
    "size",
    "transform",
    "transform_keys",
    "transform_values",
    "try_element_at",
    "zip_with",
    // ── Array ─────────────────────────────────────────────────────────────────
    "array",
    "array_append",
    "array_compact",
    "array_contains",
    "array_distinct",
    "array_except",
    "array_insert",
    "array_intersect",
    "array_join",
    "array_max",
    "array_min",
    "array_position",
    "array_prepend",
    "array_remove",
    "array_repeat",
    "array_size",
    "array_union",
    "arrays_overlap",
    "arrays_zip",
    "flatten",
    "get",
    "sequence",
    "shuffle",
    "slice",
    "sort_array",
    // ── Struct ────────────────────────────────────────────────────────────────
    "named_struct",
    "struct",
    // ── Map ───────────────────────────────────────────────────────────────────
    "create_map",
    "map_concat",
    "map_contains_key",
    "map_entries",
    "map_from_arrays",
    "map_from_entries",
    "map_keys",
    "map_values",
    "str_to_map",
    // ── Aggregate ─────────────────────────────────────────────────────────────
    "any_value",
    "approx_count_distinct",
    "approx_percentile",
    "array_agg",
    "avg",
    "bit_and",
    "bit_or",
    "bit_xor",
    "bitmap_construct_agg",
    "bitmap_or_agg",
    "bool_and",
    "bool_or",
    "collect_list",
    "collect_set",
    "corr",
    "count",
    "count_distinct",
    "count_if",
    "count_min_sketch",
    "covar_pop",
    "covar_samp",
    "every",
    "first",
    "first_value",
    "grouping",
    "grouping_id",
    "histogram_numeric",
    "hll_sketch_agg",
    "hll_union_agg",
    "kll_sketch_agg_bigint",
    "kll_sketch_agg_double",
    "kll_sketch_agg_float",
    "kurtosis",
    "last",
    "last_value",
    "listagg",
    "listagg_distinct",
    "max",
    "max_by",
    "mean",
    "median",
    "min",
    "min_by",
    "mode",
    "percentile",
    "percentile_approx",
    "product",
    "regr_avgx",
    "regr_avgy",
    "regr_count",
    "regr_intercept",
    "regr_r2",
    "regr_slope",
    "regr_sxx",
    "regr_sxy",
    "regr_syy",
    "skewness",
    "some",
    "std",
    "stddev",
    "stddev_pop",
    "stddev_samp",
    "string_agg",
    "string_agg_distinct",
    "sum",
    "sum_distinct",
    "theta_intersection_agg",
    "theta_sketch_agg",
    "theta_union_agg",
    "try_avg",
    "try_sum",
    "var_pop",
    "var_samp",
    "variance",
    // ── Window ────────────────────────────────────────────────────────────────
    "cume_dist",
    "dense_rank",
    "lag",
    "lead",
    "nth_value",
    "ntile",
    "percent_rank",
    "rank",
    "row_number",
    // ── Generator / explode ───────────────────────────────────────────────────
    "explode",
    "explode_outer",
    "inline",
    "inline_outer",
    "posexplode",
    "posexplode_outer",
    "stack",
    // ── Partitioning ──────────────────────────────────────────────────────────
    "bucket",
    "days",
    "hours",
    "months",
    "years",
    // ── CSV / JSON / XML / Variant ────────────────────────────────────────────
    "from_csv",
    "from_json",
    "from_xml",
    "get_json_object",
    "is_variant_null",
    "json_array_length",
    "json_object_keys",
    "json_tuple",
    "parse_json",
    "parse_url",
    "schema_of_csv",
    "schema_of_json",
    "schema_of_variant",
    "schema_of_variant_agg",
    "schema_of_xml",
    "to_csv",
    "to_json",
    "to_variant_object",
    "to_xml",
    "try_parse_json",
    "try_parse_url",
    "try_url_decode",
    "try_variant_get",
    "url_decode",
    "url_encode",
    "variant_get",
    // ── XPath ─────────────────────────────────────────────────────────────────
    "xpath",
    "xpath_boolean",
    "xpath_double",
    "xpath_float",
    "xpath_int",
    "xpath_long",
    "xpath_number",
    "xpath_short",
    "xpath_string",
    // ── Crypto / security ─────────────────────────────────────────────────────
    "aes_decrypt",
    "aes_encrypt",
    "try_aes_decrypt",
    // ── Misc / system ─────────────────────────────────────────────────────────
    "assert_true",
    "bitmap_bit_position",
    "bitmap_bucket_number",
    "bitmap_count",
    "current_catalog",
    "current_database",
    "current_schema",
    "current_user",
    "hll_sketch_estimate",
    "hll_union",
    "input_file_block_length",
    "input_file_block_start",
    "input_file_name",
    "java_method",
    "kll_sketch_get_n_bigint",
    "kll_sketch_get_n_double",
    "kll_sketch_get_n_float",
    "kll_sketch_get_quantile_bigint",
    "kll_sketch_get_quantile_double",
    "kll_sketch_get_quantile_float",
    "kll_sketch_get_rank_bigint",
    "kll_sketch_get_rank_double",
    "kll_sketch_get_rank_float",
    "kll_sketch_merge_bigint",
    "kll_sketch_merge_double",
    "kll_sketch_merge_float",
    "kll_sketch_to_string_bigint",
    "kll_sketch_to_string_double",
    "kll_sketch_to_string_float",
    "monotonically_increasing_id",
    "raise_error",
    "reflect",
    "session_user",
    "spark_partition_id",
    "theta_difference",
    "theta_intersection",
    "theta_sketch_estimate",
    "theta_union",
    "try_reflect",
    "typeof",
    "user",
    "uuid",
    "version",
    // ── Geospatial ────────────────────────────────────────────────────────────
    "st_asbinary",
    "st_geogfromwkb",
    "st_geomfromwkb",
    "st_setsrid",
    "st_srid",
    // ── UDF ───────────────────────────────────────────────────────────────────
    "arrow_udf",
    "arrow_udtf",
    "call_udf",
    "pandas_udf",
    "udf",
    "udtf",
    "unwrap_udt",
];

// ── Explode operations ────────────────────────────────────────────────────────

/// Functions / methods that explode an array/map column into multiple rows.
/// Used by S008 and F014.
pub static EXPLODE_OPS: &[&str] = &["explode", "explode_outer"];

// ── Non-DataFrame receiver roots ──────────────────────────────────────────────

/// Root `Name` identifiers that indicate the receiver of a method call is a
/// stdlib/utility object — never a Spark DataFrame.
///
/// Used by `is_non_dataframe_receiver()` in `rules/utils.rs` to suppress false
/// positives (e.g. `os.path.join(...)` must not trigger S002 or F016).
pub static NON_DATAFRAME_ROOTS: &[&str] = &[
    "os",
    "sys",
    "pathlib",
    "str",
    "bytes",
    "urllib",
    "posixpath",
    "ntpath",
    "shutil",
    "Path",
    "PurePath",
    "PosixPath",
    "WindowsPath",
];
